name: Deploy Hexo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install
          npm install hexo-deployer-git --save

      - name: Configure Git
        run: |
          git config --global user.email "e.lythra@qq.com"
          git config --global user.name "ElythraDev"

      - name: Deploy to GitHub
        env:
          # GitHub Actions 会自动识别这个环境变量来处理 https 认证
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install hexo-deployer-git --save
          npx hexo clean
          npx hexo generate

            # Step 5：部署到 gh-pages 分支
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          user_name: ElythraDev
          user_email: e.lythra@qq.com
